require('../css/main.scss');
var msg = require('./msg.js');
document.write(msg);
let square = x => x * x;
let add = (a, b) => a + b;
let pi = () => 3.1415;
console.log(square(5));
console.log(add(3, 4));
console.log(pi());
// debugger;
var name='Ashik'; 
document.write(`Hey There.. I'm ${name}`);